# Site settings
title: Jarrod's Blog
SEOTitle: 俊勇的博客 | Jarrod's Blog
header-img: img/post-bg-desk.jpg
email: jarrod_chen@163.com
description: "Every failure is leading towards success."
keyword: "俊勇的博客, chenjunyong, Android, Java"
url: "http://jarrod-chen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jarrod-chen/jarrod-chen.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "人生是苦的"
sidebar-avatar: /img/about-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    jarrod-chen
jianshu_username:   隽永
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus (https://disqus.com/）
#disqus_username: jarrod-chen

#  Gitalk
gitalk:
  enable: false #是否开启Gitalk评论
  clientID: cb41f24451df4a2361a8                            #生成的clientID
  clientSecret: 07a59144a615589b9903a9fac9ca98b6daf0519f    #生成的clientSecret
  repo: jarrod-chen.github.io    #仓库名称
  owner: jarrod-chen    #github用户名
  admin: jarrod-chen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·隽永",
        href: "https://www.jianshu.com/u/9f1749980922"
    },{
        title: "Android",
        href: "https://developer.android.google.cn/"
    }
]
